namespace Marketplace.Domain.Common;

/// <summary>
/// Base class for every persisted domain entity. Identifies the entity and gives it
/// a place to collect the domain events raised during its lifetime.
/// </summary>
public abstract class Entity
{
    private readonly List<IDomainEvent> _domainEvents = [];

    /// <summary>Parameterless constructor for EF Core materialisation.</summary>
    protected Entity()
    {
    }

    /// <summary>Creates an entity with a freshly generated identity.</summary>
    protected Entity(Guid id) => Id = id;

    /// <summary>Primary key. Generated by the domain, never by the database.</summary>
    public Guid Id { get; protected set; }

    /// <summary>Events raised by this entity that have not yet been dispatched.</summary>
    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    /// <summary>Records a domain event to be dispatched after the current unit of work commits.</summary>
    public void AddDomainEvent(IDomainEvent domainEvent)
    {
        ArgumentNullException.ThrowIfNull(domainEvent);
        _domainEvents.Add(domainEvent);
    }

    /// <summary>Removes and returns all pending domain events.</summary>
    public IReadOnlyCollection<IDomainEvent> ClearDomainEvents()
    {
        var events = _domainEvents.ToArray();
        _domainEvents.Clear();
        return events;
    }

    /// <summary>Entities are equal when they share a non-default identity.</summary>
    public bool Equals(Entity? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        return GetType() == other.GetType() && Id != Guid.Empty && Id == other.Id;
    }

    public override bool Equals(object? obj) => Equals(obj as Entity);

    public override int GetHashCode() => HashCode.Combine(GetType().FullName, Id);

    public static bool operator ==(Entity? left, Entity? right) =>
        left is null ? right is null : left.Equals(right);

    public static bool operator !=(Entity? left, Entity? right) => !(left == right);
}
