using Marketplace.Domain.Common;
using Marketplace.Domain.Enums;

namespace Marketplace.Domain.Sellers;

/// <summary>
/// A periodic payout statement for a seller. Generated by the daily payout job from
/// accrued commissions, so a payout can always be reconciled against the ledger.
/// </summary>
public class SellerPayout : Entity
{
    private SellerPayout()
    {
        Reference = string.Empty;
    }

    private SellerPayout(Guid id, Guid sellerId, string reference, decimal grossAmount, decimal commissionAmount, decimal netAmount, int commissionCount, DateTimeOffset periodStart, DateTimeOffset periodEnd, DateTimeOffset now)
        : base(id)
    {
        SellerId = sellerId;
        Reference = reference;
        GrossAmount = grossAmount;
        CommissionAmount = commissionAmount;
        NetAmount = netAmount;
        CommissionCount = commissionCount;
        PeriodStart = periodStart;
        PeriodEnd = periodEnd;
        Status = PayoutStatus.Pending;
        CreatedAt = now;
    }

    public Guid SellerId { get; private set; }

    /// <summary>Human-readable payout reference shown to the seller.</summary>
    public string Reference { get; private set; }

    public decimal GrossAmount { get; private set; }

    public decimal CommissionAmount { get; private set; }

    public decimal NetAmount { get; private set; }

    public int CommissionCount { get; private set; }

    public DateTimeOffset PeriodStart { get; private set; }

    public DateTimeOffset PeriodEnd { get; private set; }

    public PayoutStatus Status { get; private set; }

    public string? FailureReason { get; private set; }

    public string? TransactionReference { get; private set; }

    public DateTimeOffset? ProcessedAt { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }

    public static SellerPayout Create(
        Guid sellerId,
        string reference,
        decimal grossAmount,
        decimal commissionAmount,
        int commissionCount,
        DateTimeOffset periodStart,
        DateTimeOffset periodEnd,
        DateTimeOffset now)
    {
        Guard.NotEmpty(sellerId, nameof(sellerId));
        Guard.NotNullOrWhiteSpace(reference, nameof(reference));
        Guard.GreaterThanOrEqualToZero(grossAmount, nameof(grossAmount));

        return new SellerPayout(
            SequentialGuid.New(now),
            sellerId,
            reference.Trim(),
            grossAmount,
            commissionAmount,
            grossAmount - commissionAmount,
            commissionCount,
            periodStart,
            periodEnd,
            now);
    }

    public void MarkProcessing(DateTimeOffset now)
    {
        EnsureIn(PayoutStatus.Pending);
        Status = PayoutStatus.Processing;
    }

    public void MarkCompleted(string transactionReference, DateTimeOffset now)
    {
        EnsureIn(PayoutStatus.Pending, PayoutStatus.Processing);
        TransactionReference = transactionReference;
        Status = PayoutStatus.Completed;
        ProcessedAt = now;
    }

    public void MarkFailed(string reason, DateTimeOffset now)
    {
        EnsureIn(PayoutStatus.Pending, PayoutStatus.Processing);
        FailureReason = reason;
        Status = PayoutStatus.Failed;
        ProcessedAt = now;
    }

    public void Cancel(string reason, DateTimeOffset now)
    {
        EnsureIn(PayoutStatus.Pending);
        FailureReason = reason;
        Status = PayoutStatus.Cancelled;
        ProcessedAt = now;
    }

    private void EnsureIn(params PayoutStatus[] allowed)
    {
        if (!allowed.Contains(Status))
        {
            throw new InvalidStateTransitionException(nameof(SellerPayout), Status.ToString(), string.Join("/", allowed.Select(a => a.ToString())));
        }
    }
}
