// <auto-generated />
using System;
using Marketplace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marketplace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketplaceDbContext))]
    [Migration("20261005101734_AddReportingQueryIndexes")]
    partial class AddReportingQueryIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marketplace.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation");

                    b.HasIndex("Action", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("ActorId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_actor");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuestToken")
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestToken")
                        .IsUnique()
                        .HasDatabaseName("ux_carts_guest");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("ix_carts_activity");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_carts_user");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<bool>("SavedForLater")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_cart_items_variant");

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlists_user");

                    b.ToTable("wishlists", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WishlistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WishlistId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_wishlist_items_product");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<string>("SlugValue")
                        .IsRequired()
                        .HasColumnType("varchar(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_categories_active");

                    b.HasIndex("SlugValue")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_slug");

                    b.HasIndex("ParentId", "DisplayOrder")
                        .HasDatabaseName("ix_categories_parent_order");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Brand")
                        .HasColumnType("varchar(120)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CompareAtPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionNote")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SlugValue")
                        .IsRequired()
                        .HasColumnType("varchar(160)");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BasePrice")
                        .HasDatabaseName("ix_products_price");

                    b.HasIndex("IsFeatured")
                        .HasDatabaseName("ix_products_featured");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_products_rating");

                    b.HasIndex("SlugValue")
                        .IsUnique()
                        .HasDatabaseName("ux_products_slug");

                    b.HasIndex("CategoryId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_products_category_status");

                    b.HasIndex("SellerId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_products_seller_status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasColumnType("varchar(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_images_product_order");

                    b.ToTable("product_images", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_specs_product_order");

                    b.ToTable("product_specifications", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_product_variants_sku");

                    b.HasIndex("ProductId", "SortOrder")
                        .HasDatabaseName("ix_product_variants_product_order");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductVariantOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VariantId", "Name", "Value")
                        .HasDatabaseName("ux_variant_options");

                    b.ToTable("product_variant_options", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Commissions.Commission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AccruedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ReversalReason")
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("SellerAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_commissions_order");

                    b.HasIndex("SellerOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_commissions_seller_order");

                    b.HasIndex("SellerId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_commissions_seller");

                    b.ToTable("commissions", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Coupons.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaximumDiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PerUserLimit")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_coupons_code");

                    b.HasIndex("SellerId", "Status")
                        .HasDatabaseName("ix_coupons_seller");

                    b.HasIndex("Status", "StartsAt", "EndsAt")
                        .HasDatabaseName("ix_coupons_window");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Coupons.CouponUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_coupon_usages_order");

                    b.HasIndex("CouponId", "UserId")
                        .HasDatabaseName("ix_coupon_usages_user");

                    b.ToTable("coupon_usages", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_hash");

                    b.HasIndex("UserId", "UsedAt")
                        .HasDatabaseName("ix_password_reset_tokens_user");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(400)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId", "FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_family");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Line2")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("ix_user_addresses_user_default");

                    b.ToTable("user_addresses", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Inventory.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_variant");

                    b.HasIndex("AvailableQuantity", "Id")
                        .HasDatabaseName("ix_inventory_available");

                    b.HasIndex("SellerId", "AvailableQuantity")
                        .HasDatabaseName("ix_inventory_seller");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Inventory.InventoryReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_inventory_reservations_inventory");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_inventory_reservations_order");

                    b.HasIndex("ReleasedAt", "ExpiresAt")
                        .HasDatabaseName("ix_inventory_reservations_expiry");

                    b.ToTable("inventory_reservations", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityBefore")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(300)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_tx_variant");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_tx_reference");

                    b.HasIndex("SellerId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_tx_seller");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("varchar(300)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("ix_notifications_type");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_unread");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CouponCode")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_number");

                    b.HasIndex("PlacedAt")
                        .HasDatabaseName("ix_orders_placedat");

                    b.HasIndex("CustomerId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_customer_idempotency");

                    b.HasIndex("CustomerId", "PlacedAt")
                        .HasDatabaseName("ix_orders_customer");

                    b.HasIndex("Status", "PlacedAt")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsRefundRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductImage")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product");

                    b.HasIndex("SellerOrderId");

                    b.HasIndex("OrderId", "SellerId")
                        .HasDatabaseName("ix_order_items_order_seller");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_order_history_order");

                    b.ToTable("order_status_history", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.SellerOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CarrierName")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("EstimatedDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<decimal>("SellerEarnings")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerNote")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SellerOrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<DateTimeOffset?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_seller_orders_order");

                    b.HasIndex("SellerOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_seller_orders_number");

                    b.HasIndex("SellerId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_seller_orders_seller");

                    b.ToTable("seller_orders", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.SellerOrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SellerOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerOrderNumber")
                        .IsRequired()
                        .HasColumnType("varchar(48)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SellerOrderId", "CreatedAt")
                        .HasDatabaseName("ix_seller_order_history");

                    b.ToTable("seller_order_status_history", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GatewayPaymentId")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("GatewayRedirectUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("RefundedAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .HasDatabaseName("ix_payments_idempotency");

                    b.HasIndex("TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_reference");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("ix_payments_order_status");

                    b.HasIndex("Provider", "GatewayPaymentId")
                        .HasDatabaseName("ix_payments_gateway");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Payments.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("text");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentId", "CreatedAt")
                        .HasDatabaseName("ix_payment_tx_payment");

                    b.ToTable("payment_transactions", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Payments.PaymentWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Signature")
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("SignatureValid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_payment_webhooks_received");

                    b.HasIndex("Provider", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_webhooks_event");

                    b.ToTable("payment_webhooks", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Refunds.Refund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GatewayRefundId")
                        .HasColumnType("varchar(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_refunds_customer");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_refunds_status");

                    b.ToTable("refunds", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Refunds.RefundItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RefundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_refund_items_order_item");

                    b.HasIndex("RefundId");

                    b.ToTable("refund_items", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Reviews.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("ModerationNote")
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_reviews_order_item");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_reviews_seller");

                    b.HasIndex("ProductId", "IsVisible", "CreatedAt")
                        .HasDatabaseName("ix_reviews_product");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Reviews.ReviewReply", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId")
                        .IsUnique()
                        .HasDatabaseName("ux_review_replies_review");

                    b.ToTable("review_replies", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BankAccountName")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("BankAccountNumber")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultCommissionRate")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("LegalName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("varchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SuspensionReason")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TaxIdentityNumber")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sellers_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_sellers_user");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.SellerPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("CommissionCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_seller_payouts_reference");

                    b.HasIndex("SellerId", "Status")
                        .HasDatabaseName("ix_seller_payouts_seller_status");

                    b.ToTable("seller_payouts", (string)null);
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.SellerStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProductCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric(3,2)");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReturnPolicy")
                        .HasColumnType("varchar(4000)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShippingPolicy")
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("SlugValue")
                        .IsRequired()
                        .HasColumnType("varchar(160)");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TotalSalesCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_seller_stores_rating");

                    b.HasIndex("SellerId")
                        .IsUnique()
                        .HasDatabaseName("ux_seller_stores_seller");

                    b.HasIndex("SlugValue")
                        .IsUnique()
                        .HasDatabaseName("ux_seller_stores_slug");

                    b.ToTable("seller_stores", (string)null);
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Persistence.CouponProduct", b =>
                {
                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("CouponId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("coupon_products", (string)null);
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Persistence.ProductTag", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("product_tags", (string)null);
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.Property<Guid>("ProductsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProductTag");
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.CartItem", b =>
                {
                    b.HasOne("Marketplace.Domain.Cart.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.WishlistItem", b =>
                {
                    b.HasOne("Marketplace.Domain.Cart.Wishlist", "Wishlist")
                        .WithMany("Items")
                        .HasForeignKey("WishlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Category", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Sellers.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductSpecification", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductVariantOption", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.ProductVariant", "Variant")
                        .WithMany("Options")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("Marketplace.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Marketplace.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Identity.UserAddress", b =>
                {
                    b.HasOne("Marketplace.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Inventory.Inventory", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.ProductVariant", null)
                        .WithOne()
                        .HasForeignKey("Marketplace.Domain.Inventory.Inventory", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Marketplace.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("Marketplace.Domain.Orders.OrderAddressSnapshot", "ShippingAddressSnapshot", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("varchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("char(2)");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("varchar(60)");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Line2")
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("varchar(32)");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("RecipientName")
                                .IsRequired()
                                .HasColumnType("varchar(120)");

                            b1.Property<string>("State")
                                .HasColumnType("varchar(100)");

                            b1.HasKey("OrderId");

                            b1.ToTable("order_address_snapshots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("ShippingAddressSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Marketplace.Domain.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Orders.SellerOrder", "SellerOrder")
                        .WithMany("Items")
                        .HasForeignKey("SellerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SellerOrder");
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("Marketplace.Domain.Orders.Order", null)
                        .WithMany("History")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.SellerOrder", b =>
                {
                    b.HasOne("Marketplace.Domain.Orders.Order", "Order")
                        .WithMany("SellerOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.SellerOrderStatusHistory", b =>
                {
                    b.HasOne("Marketplace.Domain.Orders.SellerOrder", null)
                        .WithMany("History")
                        .HasForeignKey("SellerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Payments.PaymentTransaction", b =>
                {
                    b.HasOne("Marketplace.Domain.Payments.Payment", null)
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Refunds.RefundItem", b =>
                {
                    b.HasOne("Marketplace.Domain.Refunds.Refund", null)
                        .WithMany("Items")
                        .HasForeignKey("RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Reviews.ReviewReply", b =>
                {
                    b.HasOne("Marketplace.Domain.Reviews.Review", null)
                        .WithOne("Reply")
                        .HasForeignKey("Marketplace.Domain.Reviews.ReviewReply", "ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.Seller", b =>
                {
                    b.HasOne("Marketplace.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.SellerPayout", b =>
                {
                    b.HasOne("Marketplace.Domain.Sellers.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Sellers.SellerStore", b =>
                {
                    b.HasOne("Marketplace.Domain.Sellers.Seller", null)
                        .WithOne()
                        .HasForeignKey("Marketplace.Domain.Sellers.SellerStore", "SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Persistence.CouponProduct", b =>
                {
                    b.HasOne("Marketplace.Domain.Coupons.Coupon", "Coupon")
                        .WithMany()
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Marketplace.Infrastructure.Persistence.ProductTag", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Catalog.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ProductTag", b =>
                {
                    b.HasOne("Marketplace.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marketplace.Domain.Catalog.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Marketplace.Domain.Cart.Wishlist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Specifications");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Marketplace.Domain.Catalog.ProductVariant", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.Order", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Items");

                    b.Navigation("SellerOrders");
                });

            modelBuilder.Entity("Marketplace.Domain.Orders.SellerOrder", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Marketplace.Domain.Payments.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Marketplace.Domain.Refunds.Refund", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Marketplace.Domain.Reviews.Review", b =>
                {
                    b.Navigation("Reply");
                });
#pragma warning restore 612, 618
        }
    }
}
